import Report from '../models/Report.js';
import Student from '../models/Student.js';
import Company from '../models/Company.js';
import University from '../models/University.js';
import Internship from '../models/Internship.js';
import Application from '../models/Application.js';
import Placement from '../models/Placement.js';
import User from '../models/User.js';
import { logAudit } from '../services/audit.js';

// Reporting & Analytics (PKG_10 / UC013, FR12).

// Build a role-appropriate report payload: { summary, rows }.
async function buildPayload(user) {
  if (user.userType === 'university') {
    const university = await University.findOne({ userId: user._id });
    const placements = await Placement.find({ universityId: university?._id })
      .populate('internshipId', 'title')
      .populate('companyId', 'name')
      .populate({ path: 'studentId', select: 'userId major', populate: { path: 'userId', select: 'firstName lastName' } });
    const rows = placements.map((p) => ({
      student: p.studentId?.userId
        ? `${p.studentId.userId.firstName} ${p.studentId.userId.lastName}`
        : '',
      internship: p.internshipId?.title || '',
      company: p.companyId?.name || '',
      status: p.status,
      startDate: p.startDate ? new Date(p.startDate).toLocaleDateString() : '',
    }));
    return {
      title: 'University placement & completion report',
      reportType: 'university',
      summary: {
        totalPlacements: placements.length,
        completed: placements.filter((p) => p.status === 'completed').length,
        active: placements.filter((p) => p.status === 'active').length,
        pending: placements.filter((p) => p.status === 'pending').length,
      },
      rows,
    };
  }

  if (user.userType === 'company') {
    const company = await Company.findOne({ userId: user._id });
    const internships = await Internship.find({ companyId: company?._id });
    const applications = await Application.find({ companyId: company?._id });
    const rows = internships.map((i) => ({
      title: i.title,
      status: i.status,
      applications: i.applications?.length || 0,
      views: i.viewCount || 0,
    }));
    return {
      title: 'Company recruitment analytics',
      reportType: 'company',
      summary: {
        internships: internships.length,
        activeInternships: internships.filter((i) => i.status === 'active').length,
        totalApplications: applications.length,
        accepted: applications.filter((a) => a.status === 'accepted').length,
        rejected: applications.filter((a) => a.status === 'rejected').length,
      },
      rows,
    };
  }

  // admin — system-wide report
  const summary = {
    users: await User.countDocuments(),
    students: await Student.countDocuments(),
    companies: await Company.countDocuments(),
    universities: await University.countDocuments(),
    internships: await Internship.countDocuments(),
    applications: await Application.countDocuments(),
    placements: await Placement.countDocuments(),
  };
  return {
    title: 'System-wide report',
    reportType: 'audit',
    summary,
    rows: Object.entries(summary).map(([metric, value]) => ({ metric, value })),
  };
}

// @route POST /api/reports  — generate a report.
export const generateReport = async (req, res, next) => {
  try {
    const payload = await buildPayload(req.user);
    const report = await Report.create({
      type: payload.reportType,
      title: payload.title,
      generatedBy: req.user._id,
      filters: req.body.filters || {},
      payload,
    });
    await logAudit({ req, action: 'REPORT_GENERATE', entityType: 'Report', entityId: report._id });
    res.status(201).json({ success: true, report });
  } catch (err) {
    next(err);
  }
};

// @route GET /api/reports  — reports generated by the caller.
export const listReports = async (req, res, next) => {
  try {
    const reports = await Report.find({ generatedBy: req.user._id })
      .select('-payload')
      .sort('-generatedAt');
    res.json({ success: true, reports });
  } catch (err) {
    next(err);
  }
};

// @route GET /api/reports/:id
export const getReport = async (req, res, next) => {
  try {
    const report = await Report.findOne({ _id: req.params.id, generatedBy: req.user._id });
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });
    res.json({ success: true, report });
  } catch (err) {
    next(err);
  }
};

// @route GET /api/reports/:id/export  — download as CSV.
export const exportReport = async (req, res, next) => {
  try {
    const report = await Report.findOne({ _id: req.params.id, generatedBy: req.user._id });
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });
    const rows = report.payload?.rows || [];
    if (rows.length === 0) {
      return res.status(400).json({ success: false, message: 'No tabular data to export' });
    }
    const headers = Object.keys(rows[0]);
    const csv = [
      headers.join(','),
      ...rows.map((row) => headers.map((h) => JSON.stringify(row[h] ?? '')).join(',')),
    ].join('\n');
    await logAudit({ req, action: 'REPORT_EXPORT', entityType: 'Report', entityId: report._id });
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="report-${report._id}.csv"`);
    res.send(csv);
  } catch (err) {
    next(err);
  }
};
